// llm machine contract
// artifact UUIDv5: e67bec4e-cc81-54b8-8de8-e04f06503867
// execution UUIDv7: 01a0a48b-cf79-770e-a05f-eee1d6a3021e
// source revision: sha256:9478a5e17024ef21aaf5239ea2f13ffac7885ead15d95ef4607e5be55fd781bd
// state: generated static schemas; transition: checked profiles -> Plumeria build -> browser gate required
import * as css from '@plumeria/core';

export const materialSphereStyles = css.create({
  "WilliamMorrisSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#183b36",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "WilliamMorrisShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "WilliamMorrisSurface0": {
    "position": "absolute",
    "top": "12%",
    "left": "12%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#183b36",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #e4d4ac",
    "transform": "rotate(0deg)"
  },
  "WilliamMorrisSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "14%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e4d4ac",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #9bad77",
    "transform": "rotate(90deg)"
  },
  "WilliamMorrisSurface2": {
    "position": "absolute",
    "top": "44%",
    "left": "16%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#9bad77",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #ac5148",
    "transform": "rotate(180deg)"
  },
  "WilliamMorrisSurface3": {
    "position": "absolute",
    "top": "60%",
    "left": "18%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ac5148",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #183b36",
    "transform": "rotate(270deg)"
  },
  "WilliamMorrisSurface4": {
    "position": "absolute",
    "top": "76%",
    "left": "20%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#183b36",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #e4d4ac",
    "transform": "rotate(0deg)"
  },
  "WilliamMorrisSurface5": {
    "position": "absolute",
    "top": "12%",
    "left": "22%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e4d4ac",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #9bad77",
    "transform": "rotate(90deg)"
  },
  "WilliamMorrisSurface6": {
    "position": "absolute",
    "top": "28%",
    "left": "24%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#9bad77",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #ac5148",
    "transform": "rotate(180deg)"
  },
  "WilliamMorrisSurface7": {
    "position": "absolute",
    "top": "44%",
    "left": "26%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ac5148",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #183b36",
    "transform": "rotate(270deg)"
  },
  "WilliamMorrisSurface8": {
    "position": "absolute",
    "top": "60%",
    "left": "28%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#183b36",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #e4d4ac",
    "transform": "rotate(0deg)"
  },
  "WilliamMorrisSurface9": {
    "position": "absolute",
    "top": "76%",
    "left": "30%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e4d4ac",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #9bad77",
    "transform": "rotate(90deg)"
  },
  "WilliamMorrisSurface10": {
    "position": "absolute",
    "top": "12%",
    "left": "32%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#9bad77",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #ac5148",
    "transform": "rotate(180deg)"
  },
  "WilliamMorrisSurface11": {
    "position": "absolute",
    "top": "28%",
    "left": "34%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ac5148",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #183b36",
    "transform": "rotate(270deg)"
  },
  "WilliamMorrisSurface12": {
    "position": "absolute",
    "top": "44%",
    "left": "36%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#183b36",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #e4d4ac",
    "transform": "rotate(0deg)"
  },
  "WilliamMorrisSurface13": {
    "position": "absolute",
    "top": "60%",
    "left": "38%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e4d4ac",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #9bad77",
    "transform": "rotate(90deg)"
  },
  "WilliamMorrisSurface14": {
    "position": "absolute",
    "top": "76%",
    "left": "40%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#9bad77",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #ac5148",
    "transform": "rotate(180deg)"
  },
  "WilliamMorrisSurface15": {
    "position": "absolute",
    "top": "12%",
    "left": "42%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ac5148",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #183b36",
    "transform": "rotate(270deg)"
  },
  "WilliamMorrisSurface16": {
    "position": "absolute",
    "top": "28%",
    "left": "12%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#183b36",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #e4d4ac",
    "transform": "rotate(0deg)"
  },
  "WilliamMorrisSurface17": {
    "position": "absolute",
    "top": "44%",
    "left": "14%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e4d4ac",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #9bad77",
    "transform": "rotate(90deg)"
  },
  "WilliamMorrisSurface18": {
    "position": "absolute",
    "top": "60%",
    "left": "16%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#9bad77",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #ac5148",
    "transform": "rotate(180deg)"
  },
  "WilliamMorrisSurface19": {
    "position": "absolute",
    "top": "76%",
    "left": "18%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ac5148",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #183b36",
    "transform": "rotate(270deg)"
  },
  "WilliamMorrisSurface20": {
    "position": "absolute",
    "top": "12%",
    "left": "20%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#183b36",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #e4d4ac",
    "transform": "rotate(0deg)"
  },
  "WilliamMorrisSurface21": {
    "position": "absolute",
    "top": "28%",
    "left": "22%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e4d4ac",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #9bad77",
    "transform": "rotate(90deg)"
  },
  "WilliamMorrisSurface22": {
    "position": "absolute",
    "top": "44%",
    "left": "24%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#9bad77",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #ac5148",
    "transform": "rotate(180deg)"
  },
  "WilliamMorrisSurface23": {
    "position": "absolute",
    "top": "60%",
    "left": "26%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ac5148",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "15px 0 0 #183b36",
    "transform": "rotate(270deg)"
  },
  "AlphonseMuchaSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#374639",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "AlphonseMuchaShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "AlphonseMuchaSurface0": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#374639",
    "borderRadius": "50%",
    "transform": "rotate(0deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface1": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#d0b97f",
    "borderRadius": "50%",
    "transform": "rotate(30deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface2": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#eadbbc",
    "borderRadius": "50%",
    "transform": "rotate(60deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface3": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#374639",
    "borderRadius": "50%",
    "transform": "rotate(90deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface4": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#d0b97f",
    "borderRadius": "50%",
    "transform": "rotate(120deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface5": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#eadbbc",
    "borderRadius": "50%",
    "transform": "rotate(150deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface6": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#374639",
    "borderRadius": "50%",
    "transform": "rotate(180deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface7": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#d0b97f",
    "borderRadius": "50%",
    "transform": "rotate(210deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface8": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#eadbbc",
    "borderRadius": "50%",
    "transform": "rotate(240deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface9": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#374639",
    "borderRadius": "50%",
    "transform": "rotate(270deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface10": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#d0b97f",
    "borderRadius": "50%",
    "transform": "rotate(300deg) translateY(-90px)"
  },
  "AlphonseMuchaSurface11": {
    "position": "absolute",
    "top": "48%",
    "left": "48%",
    "display": "block",
    "width": "4%",
    "height": "4%",
    "backgroundColor": "#eadbbc",
    "borderRadius": "50%",
    "transform": "rotate(330deg) translateY(-90px)"
  },
  "CharlesRennieMackintoshSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#f0e6cb",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "CharlesRennieMackintoshShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "CharlesRennieMackintoshSurface0": {
    "position": "absolute",
    "top": "12%",
    "left": "12%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#f0e6cb",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #242d2b",
    "transform": "rotate(0deg)"
  },
  "CharlesRennieMackintoshSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "14%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#242d2b",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #ad6f76",
    "transform": "rotate(90deg)"
  },
  "CharlesRennieMackintoshSurface2": {
    "position": "absolute",
    "top": "44%",
    "left": "16%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ad6f76",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #f0e6cb",
    "transform": "rotate(180deg)"
  },
  "CharlesRennieMackintoshSurface3": {
    "position": "absolute",
    "top": "60%",
    "left": "18%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#f0e6cb",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #242d2b",
    "transform": "rotate(270deg)"
  },
  "CharlesRennieMackintoshSurface4": {
    "position": "absolute",
    "top": "76%",
    "left": "20%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#242d2b",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #ad6f76",
    "transform": "rotate(0deg)"
  },
  "CharlesRennieMackintoshSurface5": {
    "position": "absolute",
    "top": "12%",
    "left": "22%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ad6f76",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #f0e6cb",
    "transform": "rotate(90deg)"
  },
  "CharlesRennieMackintoshSurface6": {
    "position": "absolute",
    "top": "28%",
    "left": "24%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#f0e6cb",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #242d2b",
    "transform": "rotate(180deg)"
  },
  "CharlesRennieMackintoshSurface7": {
    "position": "absolute",
    "top": "44%",
    "left": "26%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#242d2b",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #ad6f76",
    "transform": "rotate(270deg)"
  },
  "CharlesRennieMackintoshSurface8": {
    "position": "absolute",
    "top": "60%",
    "left": "28%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ad6f76",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #f0e6cb",
    "transform": "rotate(0deg)"
  },
  "CharlesRennieMackintoshSurface9": {
    "position": "absolute",
    "top": "76%",
    "left": "30%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#f0e6cb",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #242d2b",
    "transform": "rotate(90deg)"
  },
  "CharlesRennieMackintoshSurface10": {
    "position": "absolute",
    "top": "12%",
    "left": "32%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#242d2b",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #ad6f76",
    "transform": "rotate(180deg)"
  },
  "CharlesRennieMackintoshSurface11": {
    "position": "absolute",
    "top": "28%",
    "left": "34%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ad6f76",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #f0e6cb",
    "transform": "rotate(270deg)"
  },
  "CharlesRennieMackintoshSurface12": {
    "position": "absolute",
    "top": "44%",
    "left": "36%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#f0e6cb",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #242d2b",
    "transform": "rotate(0deg)"
  },
  "CharlesRennieMackintoshSurface13": {
    "position": "absolute",
    "top": "60%",
    "left": "38%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#242d2b",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #ad6f76",
    "transform": "rotate(90deg)"
  },
  "CharlesRennieMackintoshSurface14": {
    "position": "absolute",
    "top": "76%",
    "left": "40%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ad6f76",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #f0e6cb",
    "transform": "rotate(180deg)"
  },
  "CharlesRennieMackintoshSurface15": {
    "position": "absolute",
    "top": "12%",
    "left": "42%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#f0e6cb",
    "borderRadius": "90% 10% 85% 15%",
    "boxShadow": "20px 0 0 #242d2b",
    "transform": "rotate(270deg)"
  },
  "PietMondrianSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#e5dfcf",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "PietMondrianShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "PietMondrianSurface0": {
    "position": "absolute",
    "top": "12%",
    "left": "12%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#e5dfcf",
    "border": "3px solid #1c2222",
    "transform": "rotate(0deg)"
  },
  "PietMondrianSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "14%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#1c2222",
    "border": "3px solid #1c2222",
    "transform": "rotate(90deg)"
  },
  "PietMondrianSurface2": {
    "position": "absolute",
    "top": "44%",
    "left": "16%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#cf4436",
    "border": "3px solid #1c2222",
    "transform": "rotate(180deg)"
  },
  "PietMondrianSurface3": {
    "position": "absolute",
    "top": "60%",
    "left": "18%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#e4b536",
    "border": "3px solid #1c2222",
    "transform": "rotate(270deg)"
  },
  "PietMondrianSurface4": {
    "position": "absolute",
    "top": "76%",
    "left": "20%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#366184",
    "border": "3px solid #1c2222",
    "transform": "rotate(0deg)"
  },
  "PietMondrianSurface5": {
    "position": "absolute",
    "top": "12%",
    "left": "22%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#e5dfcf",
    "border": "3px solid #1c2222",
    "transform": "rotate(90deg)"
  },
  "PietMondrianSurface6": {
    "position": "absolute",
    "top": "28%",
    "left": "24%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#1c2222",
    "border": "3px solid #1c2222",
    "transform": "rotate(180deg)"
  },
  "PietMondrianSurface7": {
    "position": "absolute",
    "top": "44%",
    "left": "26%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#cf4436",
    "border": "3px solid #1c2222",
    "transform": "rotate(270deg)"
  },
  "PietMondrianSurface8": {
    "position": "absolute",
    "top": "60%",
    "left": "28%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#e4b536",
    "border": "3px solid #1c2222",
    "transform": "rotate(0deg)"
  },
  "PietMondrianSurface9": {
    "position": "absolute",
    "top": "76%",
    "left": "30%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#366184",
    "border": "3px solid #1c2222",
    "transform": "rotate(90deg)"
  },
  "PietMondrianSurface10": {
    "position": "absolute",
    "top": "12%",
    "left": "32%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#e5dfcf",
    "border": "3px solid #1c2222",
    "transform": "rotate(180deg)"
  },
  "PietMondrianSurface11": {
    "position": "absolute",
    "top": "28%",
    "left": "34%",
    "display": "block",
    "width": "35%",
    "height": "25%",
    "backgroundColor": "#1c2222",
    "border": "3px solid #1c2222",
    "transform": "rotate(270deg)"
  },
  "GerritRietveldSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#1b2323",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "GerritRietveldShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "GerritRietveldSurface0": {
    "position": "absolute",
    "top": "12%",
    "left": "12%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#1b2323",
    "border": "1px solid #cb4438",
    "transform": "perspective(600px) rotateY(90deg)",
    "opacity": "0.9"
  },
  "GerritRietveldSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "14%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#cb4438",
    "border": "1px solid #cb4438",
    "transform": "perspective(600px) rotateX(-90deg)",
    "opacity": "0.9"
  },
  "GerritRietveldSurface2": {
    "position": "absolute",
    "top": "44%",
    "left": "16%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#e2b833",
    "border": "1px solid #cb4438",
    "transform": "perspective(600px) rotateY(0deg)",
    "opacity": "0.9"
  },
  "GerritRietveldSurface3": {
    "position": "absolute",
    "top": "60%",
    "left": "18%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#365d82",
    "border": "1px solid #cb4438",
    "transform": "perspective(600px) rotateY(90deg)",
    "opacity": "0.9"
  },
  "GerritRietveldSurface4": {
    "position": "absolute",
    "top": "76%",
    "left": "20%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#1b2323",
    "border": "1px solid #cb4438",
    "transform": "perspective(600px) rotateX(-90deg)",
    "opacity": "0.9"
  },
  "GerritRietveldSurface5": {
    "position": "absolute",
    "top": "12%",
    "left": "22%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#cb4438",
    "border": "1px solid #cb4438",
    "transform": "perspective(600px) rotateY(0deg)",
    "opacity": "0.9"
  },
  "EttoreSottsassSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#d46476",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "EttoreSottsassShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "EttoreSottsassSurface0": {
    "position": "absolute",
    "top": "12%",
    "left": "12%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#d46476",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(0deg)"
  },
  "EttoreSottsassSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "14%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e7bb4b",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(45deg)"
  },
  "EttoreSottsassSurface2": {
    "position": "absolute",
    "top": "44%",
    "left": "16%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#65a0a0",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(90deg)"
  },
  "EttoreSottsassSurface3": {
    "position": "absolute",
    "top": "60%",
    "left": "18%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e7ddc9",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(135deg)"
  },
  "EttoreSottsassSurface4": {
    "position": "absolute",
    "top": "76%",
    "left": "20%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#272731",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(180deg)"
  },
  "EttoreSottsassSurface5": {
    "position": "absolute",
    "top": "12%",
    "left": "22%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#d46476",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(225deg)"
  },
  "EttoreSottsassSurface6": {
    "position": "absolute",
    "top": "28%",
    "left": "24%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e7bb4b",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(270deg)"
  },
  "EttoreSottsassSurface7": {
    "position": "absolute",
    "top": "44%",
    "left": "26%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#65a0a0",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(315deg)"
  },
  "EttoreSottsassSurface8": {
    "position": "absolute",
    "top": "60%",
    "left": "28%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e7ddc9",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(0deg)"
  },
  "EttoreSottsassSurface9": {
    "position": "absolute",
    "top": "76%",
    "left": "30%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#272731",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(45deg)"
  },
  "EttoreSottsassSurface10": {
    "position": "absolute",
    "top": "12%",
    "left": "32%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#d46476",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(90deg)"
  },
  "EttoreSottsassSurface11": {
    "position": "absolute",
    "top": "28%",
    "left": "34%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e7bb4b",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(135deg)"
  },
  "EttoreSottsassSurface12": {
    "position": "absolute",
    "top": "44%",
    "left": "36%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#65a0a0",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(180deg)"
  },
  "EttoreSottsassSurface13": {
    "position": "absolute",
    "top": "60%",
    "left": "38%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e7ddc9",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(225deg)"
  },
  "EttoreSottsassSurface14": {
    "position": "absolute",
    "top": "76%",
    "left": "12%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#272731",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(270deg)"
  },
  "EttoreSottsassSurface15": {
    "position": "absolute",
    "top": "12%",
    "left": "14%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#d46476",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(315deg)"
  },
  "EttoreSottsassSurface16": {
    "position": "absolute",
    "top": "28%",
    "left": "16%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e7bb4b",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(0deg)"
  },
  "EttoreSottsassSurface17": {
    "position": "absolute",
    "top": "44%",
    "left": "18%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#65a0a0",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(45deg)"
  },
  "EttoreSottsassSurface18": {
    "position": "absolute",
    "top": "60%",
    "left": "20%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e7ddc9",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(90deg)"
  },
  "EttoreSottsassSurface19": {
    "position": "absolute",
    "top": "76%",
    "left": "22%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#272731",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(135deg)"
  },
  "EttoreSottsassSurface20": {
    "position": "absolute",
    "top": "12%",
    "left": "24%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#d46476",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(180deg)"
  },
  "EttoreSottsassSurface21": {
    "position": "absolute",
    "top": "28%",
    "left": "26%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e7bb4b",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(225deg)"
  },
  "EttoreSottsassSurface22": {
    "position": "absolute",
    "top": "44%",
    "left": "28%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#65a0a0",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(270deg)"
  },
  "EttoreSottsassSurface23": {
    "position": "absolute",
    "top": "60%",
    "left": "30%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e7ddc9",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e7bb4b 5px,#e7bb4b 7px)",
    "transform": "rotate(315deg)"
  },
  "HerbertBayerSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#e8deca",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "HerbertBayerShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "HerbertBayerSurface0": {
    "position": "absolute",
    "top": "12%",
    "left": "12%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "transparent",
    "border": "7px solid #e8deca",
    "borderRadius": "50%",
    "transform": "rotate(0deg)"
  },
  "HerbertBayerSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "14%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "transparent",
    "border": "7px solid #212627",
    "borderRadius": "0%",
    "transform": "rotate(90deg)"
  },
  "HerbertBayerSurface2": {
    "position": "absolute",
    "top": "44%",
    "left": "16%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "transparent",
    "border": "7px solid #c8503d",
    "borderRadius": "50%",
    "transform": "rotate(180deg)"
  },
  "HerbertBayerSurface3": {
    "position": "absolute",
    "top": "60%",
    "left": "18%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "transparent",
    "border": "7px solid #e8deca",
    "borderRadius": "0%",
    "transform": "rotate(270deg)"
  },
  "HerbertBayerSurface4": {
    "position": "absolute",
    "top": "76%",
    "left": "20%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "transparent",
    "border": "7px solid #212627",
    "borderRadius": "50%",
    "transform": "rotate(0deg)"
  },
  "HerbertBayerSurface5": {
    "position": "absolute",
    "top": "12%",
    "left": "22%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "transparent",
    "border": "7px solid #c8503d",
    "borderRadius": "0%",
    "transform": "rotate(90deg)"
  },
  "HerbertBayerSurface6": {
    "position": "absolute",
    "top": "28%",
    "left": "24%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "transparent",
    "border": "7px solid #e8deca",
    "borderRadius": "50%",
    "transform": "rotate(180deg)"
  },
  "HerbertBayerSurface7": {
    "position": "absolute",
    "top": "44%",
    "left": "26%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "transparent",
    "border": "7px solid #212627",
    "borderRadius": "0%",
    "transform": "rotate(270deg)"
  },
  "JosefMullerBrockmannSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#ddd6bf",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "JosefMullerBrockmannShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "JosefMullerBrockmannSurface0": {
    "position": "absolute",
    "top": "0px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#ddd6bf",
    "borderRadius": "0px"
  },
  "JosefMullerBrockmannSurface1": {
    "position": "absolute",
    "top": "12px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#283131",
    "borderRadius": "0px"
  },
  "JosefMullerBrockmannSurface2": {
    "position": "absolute",
    "top": "24px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#b65345",
    "borderRadius": "0px"
  },
  "JosefMullerBrockmannSurface3": {
    "position": "absolute",
    "top": "36px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#ddd6bf",
    "borderRadius": "0px"
  },
  "JosefMullerBrockmannSurface4": {
    "position": "absolute",
    "top": "48px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#283131",
    "borderRadius": "0px"
  },
  "JosefMullerBrockmannSurface5": {
    "position": "absolute",
    "top": "60px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#b65345",
    "borderRadius": "0px"
  },
  "JosefMullerBrockmannSurface6": {
    "position": "absolute",
    "top": "72px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#ddd6bf",
    "borderRadius": "0px"
  },
  "JosefMullerBrockmannSurface7": {
    "position": "absolute",
    "top": "84px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#283131",
    "borderRadius": "0px"
  },
  "MassimoVignelliSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#ded8c7",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "MassimoVignelliShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "MassimoVignelliSurface0": {
    "position": "absolute",
    "top": "12%",
    "left": "12%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#ded8c7",
    "borderRadius": "3px",
    "transform": "rotate(0deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "14%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#cb5845",
    "borderRadius": "3px",
    "transform": "rotate(45deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface2": {
    "position": "absolute",
    "top": "44%",
    "left": "16%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#476c91",
    "borderRadius": "3px",
    "transform": "rotate(90deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface3": {
    "position": "absolute",
    "top": "60%",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#bba042",
    "borderRadius": "3px",
    "transform": "rotate(135deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface4": {
    "position": "absolute",
    "top": "76%",
    "left": "20%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#ded8c7",
    "borderRadius": "3px",
    "transform": "rotate(180deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface5": {
    "position": "absolute",
    "top": "12%",
    "left": "22%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#cb5845",
    "borderRadius": "3px",
    "transform": "rotate(225deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface6": {
    "position": "absolute",
    "top": "28%",
    "left": "24%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#476c91",
    "borderRadius": "3px",
    "transform": "rotate(270deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface7": {
    "position": "absolute",
    "top": "44%",
    "left": "26%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#bba042",
    "borderRadius": "3px",
    "transform": "rotate(315deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface8": {
    "position": "absolute",
    "top": "60%",
    "left": "28%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#ded8c7",
    "borderRadius": "3px",
    "transform": "rotate(0deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface9": {
    "position": "absolute",
    "top": "76%",
    "left": "30%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#cb5845",
    "borderRadius": "3px",
    "transform": "rotate(45deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface10": {
    "position": "absolute",
    "top": "12%",
    "left": "32%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#476c91",
    "borderRadius": "3px",
    "transform": "rotate(90deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface11": {
    "position": "absolute",
    "top": "28%",
    "left": "34%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#bba042",
    "borderRadius": "3px",
    "transform": "rotate(135deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface12": {
    "position": "absolute",
    "top": "44%",
    "left": "12%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#ded8c7",
    "borderRadius": "3px",
    "transform": "rotate(180deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface13": {
    "position": "absolute",
    "top": "60%",
    "left": "14%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#cb5845",
    "borderRadius": "3px",
    "transform": "rotate(225deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface14": {
    "position": "absolute",
    "top": "76%",
    "left": "16%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#476c91",
    "borderRadius": "3px",
    "transform": "rotate(270deg)",
    "transformOrigin": "0% 50%"
  },
  "MassimoVignelliSurface15": {
    "position": "absolute",
    "top": "12%",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#bba042",
    "borderRadius": "3px",
    "transform": "rotate(315deg)",
    "transformOrigin": "0% 50%"
  },
  "DieterRamsSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#d9d9ce",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "DieterRamsShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "DieterRamsSurface0": {
    "position": "absolute",
    "top": "0px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#d9d9ce",
    "borderRadius": "2px"
  },
  "DieterRamsSurface1": {
    "position": "absolute",
    "top": "16px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#454d4a",
    "borderRadius": "2px"
  },
  "DieterRamsSurface2": {
    "position": "absolute",
    "top": "32px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#b2b7aa",
    "borderRadius": "2px"
  },
  "DieterRamsSurface3": {
    "position": "absolute",
    "top": "48px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#d9d9ce",
    "borderRadius": "2px"
  },
  "DieterRamsSurface4": {
    "position": "absolute",
    "top": "64px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#454d4a",
    "borderRadius": "2px"
  },
  "DieterRamsSurface5": {
    "position": "absolute",
    "top": "80px",
    "left": "18%",
    "display": "block",
    "width": "64%",
    "height": "3%",
    "backgroundColor": "#b2b7aa",
    "borderRadius": "2px"
  },
  "NaotoFukasawaSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#e4e3d8",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "NaotoFukasawaShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "NaotoFukasawaSurface0": {
    "position": "absolute",
    "top": "25%",
    "left": "25%",
    "display": "block",
    "width": "50%",
    "height": "50%",
    "backgroundColor": "#e4e3d8",
    "border": "10px solid #5d6763",
    "borderRadius": "50%",
    "boxShadow": "0 60px 0 -20px #5d6763"
  },
  "ReiKawakuboSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#1a2025",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "ReiKawakuboShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "ReiKawakuboSurface0": {
    "position": "absolute",
    "top": "12%",
    "left": "12%",
    "display": "block",
    "width": "20%",
    "height": "65%",
    "backgroundColor": "#1a2025",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(0deg)"
  },
  "ReiKawakuboSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "14%",
    "display": "block",
    "width": "41%",
    "height": "65%",
    "backgroundColor": "#42494e",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(46deg)"
  },
  "ReiKawakuboSurface2": {
    "position": "absolute",
    "top": "44%",
    "left": "16%",
    "display": "block",
    "width": "22%",
    "height": "65%",
    "backgroundColor": "#737879",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(92deg)"
  },
  "ReiKawakuboSurface3": {
    "position": "absolute",
    "top": "60%",
    "left": "18%",
    "display": "block",
    "width": "43%",
    "height": "65%",
    "backgroundColor": "#1a2025",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(138deg)"
  },
  "ReiKawakuboSurface4": {
    "position": "absolute",
    "top": "76%",
    "left": "20%",
    "display": "block",
    "width": "24%",
    "height": "65%",
    "backgroundColor": "#42494e",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(184deg)"
  },
  "ReiKawakuboSurface5": {
    "position": "absolute",
    "top": "12%",
    "left": "22%",
    "display": "block",
    "width": "45%",
    "height": "65%",
    "backgroundColor": "#737879",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(230deg)"
  },
  "ReiKawakuboSurface6": {
    "position": "absolute",
    "top": "28%",
    "left": "24%",
    "display": "block",
    "width": "26%",
    "height": "65%",
    "backgroundColor": "#1a2025",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(276deg)"
  },
  "ReiKawakuboSurface7": {
    "position": "absolute",
    "top": "44%",
    "left": "26%",
    "display": "block",
    "width": "47%",
    "height": "65%",
    "backgroundColor": "#42494e",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(322deg)"
  },
  "ReiKawakuboSurface8": {
    "position": "absolute",
    "top": "60%",
    "left": "28%",
    "display": "block",
    "width": "28%",
    "height": "65%",
    "backgroundColor": "#737879",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(8deg)"
  },
  "ReiKawakuboSurface9": {
    "position": "absolute",
    "top": "76%",
    "left": "30%",
    "display": "block",
    "width": "49%",
    "height": "65%",
    "backgroundColor": "#1a2025",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(54deg)"
  },
  "ReiKawakuboSurface10": {
    "position": "absolute",
    "top": "12%",
    "left": "32%",
    "display": "block",
    "width": "20%",
    "height": "65%",
    "backgroundColor": "#42494e",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(100deg)"
  },
  "ReiKawakuboSurface11": {
    "position": "absolute",
    "top": "28%",
    "left": "34%",
    "display": "block",
    "width": "41%",
    "height": "65%",
    "backgroundColor": "#737879",
    "boxShadow": "inset 2px 2px 8px #737879",
    "clipPath": "polygon(0% 0%,100% 20%,65% 100%,15% 75%)",
    "transform": "rotate(146deg)"
  },
  "CharlesEamesSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#95664b",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "CharlesEamesShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "CharlesEamesSurface0": {
    "position": "absolute",
    "top": "14%",
    "left": "12%",
    "display": "block",
    "width": "68%",
    "height": "42%",
    "backgroundColor": "#95664b",
    "border": "6px solid #dfc6a0",
    "borderRadius": "48%"
  },
  "CharlesEamesSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "20%",
    "display": "block",
    "width": "68%",
    "height": "42%",
    "backgroundColor": "#dfc6a0",
    "border": "6px solid #dfc6a0",
    "borderRadius": "48%"
  },
  "CharlesEamesSurface2": {
    "position": "absolute",
    "top": "42%",
    "left": "28%",
    "display": "block",
    "width": "68%",
    "height": "42%",
    "backgroundColor": "#303637",
    "border": "6px solid #dfc6a0",
    "borderRadius": "48%"
  },
  "RayEamesSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#ce695d",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "RayEamesShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "RayEamesSurface0": {
    "position": "absolute",
    "top": "12%",
    "left": "12%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ce695d",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(0deg)"
  },
  "RayEamesSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "14%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e5c477",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(45deg)"
  },
  "RayEamesSurface2": {
    "position": "absolute",
    "top": "44%",
    "left": "16%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#6d9c9a",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(90deg)"
  },
  "RayEamesSurface3": {
    "position": "absolute",
    "top": "60%",
    "left": "18%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#dab5c1",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(135deg)"
  },
  "RayEamesSurface4": {
    "position": "absolute",
    "top": "76%",
    "left": "20%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#414945",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(180deg)"
  },
  "RayEamesSurface5": {
    "position": "absolute",
    "top": "12%",
    "left": "22%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ce695d",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(225deg)"
  },
  "RayEamesSurface6": {
    "position": "absolute",
    "top": "28%",
    "left": "24%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e5c477",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(270deg)"
  },
  "RayEamesSurface7": {
    "position": "absolute",
    "top": "44%",
    "left": "26%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#6d9c9a",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(315deg)"
  },
  "RayEamesSurface8": {
    "position": "absolute",
    "top": "60%",
    "left": "28%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#dab5c1",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(0deg)"
  },
  "RayEamesSurface9": {
    "position": "absolute",
    "top": "76%",
    "left": "30%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#414945",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(45deg)"
  },
  "RayEamesSurface10": {
    "position": "absolute",
    "top": "12%",
    "left": "32%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ce695d",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(90deg)"
  },
  "RayEamesSurface11": {
    "position": "absolute",
    "top": "28%",
    "left": "34%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#e5c477",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(135deg)"
  },
  "RayEamesSurface12": {
    "position": "absolute",
    "top": "44%",
    "left": "36%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#6d9c9a",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(180deg)"
  },
  "RayEamesSurface13": {
    "position": "absolute",
    "top": "60%",
    "left": "38%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#dab5c1",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(225deg)"
  },
  "RayEamesSurface14": {
    "position": "absolute",
    "top": "76%",
    "left": "40%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#414945",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(270deg)"
  },
  "RayEamesSurface15": {
    "position": "absolute",
    "top": "12%",
    "left": "42%",
    "display": "block",
    "width": "18%",
    "height": "18%",
    "backgroundColor": "#ce695d",
    "backgroundImage": "repeating-linear-gradient(45deg,transparent 0px,transparent 5px,#e5c477 5px,#e5c477 7px)",
    "transform": "rotate(315deg)"
  },
  "WalterGropiusSphere": {
    "position": "relative",
    "width": "240px",
    "height": "240px",
    "overflow": "hidden",
    "backgroundColor": "#cfdbd8",
    "borderRadius": "50%",
    "isolation": "isolate"
  },
  "WalterGropiusShading": {
    "position": "absolute",
    "inset": "0px",
    "pointerEvents": "none",
    "backgroundImage": "radial-gradient(circle at 28% 24%,#ffffff66 0%,transparent 42%,#00000099 100%)",
    "borderRadius": "50%",
    "boxShadow": "inset -12px -16px 24px #00000055"
  },
  "WalterGropiusSurface0": {
    "position": "absolute",
    "top": "12%",
    "left": "12%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#cfdbd8",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateY(90deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface1": {
    "position": "absolute",
    "top": "28%",
    "left": "14%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#334549",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateX(-90deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface2": {
    "position": "absolute",
    "top": "44%",
    "left": "16%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#b6beb6",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateY(0deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface3": {
    "position": "absolute",
    "top": "60%",
    "left": "18%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#cfdbd8",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateY(90deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface4": {
    "position": "absolute",
    "top": "76%",
    "left": "20%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#334549",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateX(-90deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface5": {
    "position": "absolute",
    "top": "12%",
    "left": "22%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#b6beb6",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateY(0deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface6": {
    "position": "absolute",
    "top": "28%",
    "left": "24%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#cfdbd8",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateY(90deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface7": {
    "position": "absolute",
    "top": "44%",
    "left": "26%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#334549",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateX(-90deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface8": {
    "position": "absolute",
    "top": "60%",
    "left": "28%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#b6beb6",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateY(0deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface9": {
    "position": "absolute",
    "top": "76%",
    "left": "30%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#cfdbd8",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateY(90deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface10": {
    "position": "absolute",
    "top": "12%",
    "left": "32%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#334549",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateX(-90deg)",
    "opacity": "0.45"
  },
  "WalterGropiusSurface11": {
    "position": "absolute",
    "top": "28%",
    "left": "34%",
    "display": "block",
    "width": "48%",
    "height": "44%",
    "backgroundColor": "#b6beb6",
    "border": "1px solid #334549",
    "transform": "perspective(600px) rotateY(0deg)",
    "opacity": "0.45"
  }
});
